changelog:
  exclude:
    labels:
      - ignore

  categories:
    - title: Database
      labels:
        - db
        
    - title: Features
      labels:
        - feature

    - title: Bug fixes
      labels:
        - bug

    - title: Dependencies
      labels:
        - dependencie

    - title: Other changes
      labels:
        - '*'
