name: CI

on:
  workflow_dispatch:
    inputs:
      probers_enabled:
        description: 'Runs probers when checked'
        default: true
        required: true
        type: boolean
  schedule:
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: a
        run: echo a
        
      - name: b
        if: ${{ github.event.inputs.probers_enabled == 'true' }}
        run: echo b
        
      - name: c
        run: echo c

      - name: print details
        env:
          DETAILS: ${{ toJson(github.events) }}
        run: echo $DETAILS
        
      - name: print inputs
        env:
          DETAILS: ${{ toJson(github.events.inputs) }}
        run: echo $DETAILS
        
      - name: print inputs probers_enabled
        env:
          DETAILS: ${{ toJson(github.events.inputs.probers_enabled) }}
        run: echo $DETAILS
        
      - name: print schedule
        env:
          DETAILS: ${{ toJson(github.events.schedule) }}
        run: echo $DETAILS
